---
- name: Playbook for filters
  hosts: localhost
  gather_facts: no
  vars:
          jarlist: [1,1,1,1,1,5]
          repeatlist: [1,2,2,2,4,4,4,4,9,9,9,9]
          repeat2list: [1,2,3,4,5,6,7]
          complexlist: [6,7,8,9,[10,22,55,87]]
          test_list:
                  - '192.168.2.1'
                  - '10.0.0.1'
                  - 'host.example.org'
                  - '192.168.70.0/24'
                  - 'fe80::100/10'
                  - True
                  - 'Witcher3 The Wild Hunt'
                  - 'Earl Grey tea, hot'
          mytest_string: 'ncc1701 uss enterprise'
          myaddresses: ['192.168.2.101', '10.0.3.50', '171.172.32.1']

  tasks:
          - name: Example of min() filter
            debug:
                    msg: "'{{ jarlist | min }}'"

          - name: Example of flatten() filter
            debug:
                    msg: "'{{ complexlist | flatten }}'"

          - name: Example of unique() filter
            debug:
                    msg: "'{{ repeatlist | unique }}'"

          - name: Example of diff() filter
            debug:
                    msg: "'{{ repeatlist | difference(repeat2list) }}'"

          - name: Example of sleep() filter
            pause:
                    seconds: "{{ sleeptime | default(0) }}"

          - name: Example of ipaddr() filter
            debug:
                    msg: "{{ test_list | ipaddr }}"

          - name: Example of random_mac() filter
            debug:
                    msg: "{{ '52:54:00' | random_mac }}"

          - name: Example of random_mac() filter
            debug:
                    msg: "ahh, but is it A B C or D???"
            when: mytest_string.endswith('prise')

          - name: Example of capitalize() jinja
            debug:
                    msg: "{{ mytest_string | capitalize }}"

          - name: Example of capitalize() pythonic
            debug:
                    var: mytest_string.capitalize()

          - name: Example of scope
            debug:
                    msg: "{{ (myaddresses|ipaddr('10.0.0.0/8'))[0].split('.')[3] }}"
