---
- name: Prompting playbook
  hosts: localhost
  gather_facts: no
  vars:
  vars_prompt:
          - name: "yourpasswdprompt" # Name the variable
            prompt: "What is your password" # What to ask the user
            private: yes # Make sure to not echo to screen
            encrypt: "sha512_crypt" # Any encryption value available from crypt
            confim: no
            default: "qwerty"

  tasks:
          - name: Print the answer
            debug:
                    var: yourpasswdprompt
...
