---
- name: My first playbook
  hosts: localhost
  vars:
          STATE: absent
          APP: bastet
  tasks:
          - name: Deploy software from aptitude directory for ubuntu
            when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
            apt:
                    name: "{{ APP }}"
                    state: "{{ STATE }}"
            become: yes
            register: RESULTS

          - debug:
                  var: RESULTS
...
